[AT_RU_0_1] intial base setup including prettier and eslint
jtg-induction/AYUSH_TIWARI_ASSIGNMENT_2 pull request #1
Opened 2024-08-01 12:37 UTC by tiwari00ayush

## What type of PR is this? (check all applicable)

-   [ ] Refactor
-   [x] Feature
-   [ ] Bug Fix
-   [ ] Optimization
-   [ ] Documentation Update

## Descripitions
1. Added prettier for auto formatting.
2. Added eslint for error detection and enforcing best practices.
3. Added pre commit hook using husky and lint-staged for auto linting and formatting before commit.

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules

## Test

-   [ ] Keyboard accessibility
-   [ ] Pixel Perfect testing
-   [ ] Cross browser testing

2024-08-01 13:49 UTC, thisisankur0 commented
![image](https://github.com/user-attachments/assets/58ffb21d-97d4-46cb-80c6-f4ee22aeda73)

2024-08-01 22:55 UTC, thisisankur0 requested changes

2024-08-01 22:55 UTC, thisisankur0 commented on .eslintrc.cjs
> +        'plugin:react-hooks/recommended', // extends the react-hooks recommended rules
Nit: Please don't add comments which doesn't convey anything.

2024-08-01 22:55 UTC, thisisankur0 commented on tsconfig.app.json
> +        "noFallthroughCasesInSwitch": true
These rules defined here doesn't show up inside the linter.

2024-08-01 22:55 UTC, thisisankur0 commented on tsconfig.app.json
> +        "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
Why is this added?

2024-08-01 22:55 UTC, thisisankur0 commented on tsconfig.app.json
> +        "useDefineForClassFields": true,
What is the use case for this in our project?

2024-08-01 22:55 UTC, thisisankur0 commented on .husky/pre-commit
> +npx lint-staged
Also pre-commit hook is not working for me.

2024-08-01 22:55 UTC, thisisankur0 commented on .prettierignore
> +node_modules
This will format lock file

2024-08-01 22:55 UTC, thisisankur0 commented on index.html
> +        <title>Vite + React + TS</title>
Update Title

2024-08-01 22:55 UTC, thisisankur0 commented on package.json
> +        "preview": "vite preview"
Missing format command

2024-08-01 22:55 UTC, thisisankur0 commented on .lintstagedrc
> +    "prettier --write"
This command will overwrite your file

2024-08-01 22:55 UTC, thisisankur0 commented on .lintstagedrc
> +    "eslint --fix",
Missing a flag for checking number of errors.

2024-08-01 22:55 UTC, thisisankur0 commented on .eslintrc.cjs
> +        'plugin:@typescript-eslint/recommended', // extends the typescript-eslint recommended rules
Missing some more plugin rules, please explore and add them (only extend rules **not** plugin).

2024-08-01 22:55 UTC, thisisankur0 commented on .prettierignore
> +node_modules
Missing EOF. Please self review properly

2024-08-01 22:55 UTC, thisisankur0 commented on .husky/pre-commit
> +npx lint-staged
EOF?

2024-08-01 22:55 UTC, thisisankur0 commented on .gitignore
> +dist
EOF missing here too.

2024-08-01 22:55 UTC, thisisankur0 commented on tsconfig.node.json
> +        "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.node.tsbuildinfo",
Same what is the use case for this key?

2024-08-01 22:55 UTC, thisisankur0 commented on package.json
> +        "lint": "eslint . --ext ts,tsx",
Why are these file extensions defined here?

2024-08-01 22:55 UTC, thisisankur0 commented on index.html
> +        <link rel="icon" type="image/svg+xml" href="/vite.svg" />
Remove this

2024-08-02 05:33 UTC, tiwari00ayush commented on src/main.tsx
> +import './index.css';
okay, will remember from next time

2024-08-02 05:33 UTC, tiwari00ayush commented on .github/pull_request_template.md
> +-   [ ] Documentation Update
okay sure

2024-08-02 05:37 UTC, tiwari00ayush commented on readme.md
> +5. Open a Pull request
okay sure, will remove from here.

2024-08-02 05:47 UTC, tiwari00ayush commented on .prettierignore
> +node_modules
will not repeat.

2024-08-02 06:11 UTC, tiwari00ayush commented on .husky/pre-commit
> +npx lint-staged
okay i will check why it may not be working

2024-08-02 06:20 UTC, tiwari00ayush commented on .lintstagedrc
> +    "eslint --fix",
number of error or warning ?

2024-08-02 06:24 UTC, tiwari00ayush commented on .lintstagedrc
> +  "**/*.{ts,tsx,json}": [
No, we can't lint json with eslint i just want to format the json files

2024-08-02 06:25 UTC, tiwari00ayush commented on .lintstagedrc
> +    "prettier --write"
it will just format the files not change any logic, so there should be no problem

2024-08-02 09:17 UTC, thisisankur0 commented on .lintstagedrc
> +    "eslint --fix",
Include both

2024-08-03 05:56 UTC, tiwari00ayush commented on .eslintrc.cjs
> +        'react-refresh', // useful for hot reloading during development
fast refresh provided by vite only works properly when jsx or tsx file export jsx or tsx code not constant or util function. To avoid that we use react-refresh plugin so that we do not mistakely export contant or util function through tsx file
![Screenshot from 2024-08-03 11-26-29](https://github.com/user-attachments/assets/b0ee548f-de87-4f6c-8a83-299c21291b87)

2024-08-03 06:47 UTC, tiwari00ayush commented on tsconfig.app.json
> +        "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
This is where TypeScript stores information about what it has already checked so it can skip over unchanged parts next time.

2024-08-03 06:49 UTC, tiwari00ayush commented on tsconfig.app.json
> +        "useDefineForClassFields": true,
TypeScript adopts the modern JavaScript behavior for initializing properties directly on the class instance, making your code more predictable and in line with modern standards.

2024-08-03 06:50 UTC, tiwari00ayush commented on tsconfig.app.json
> +        "noFallthroughCasesInSwitch": true
will add more rules in eslint

2024-08-05 01:01 UTC, thisisankur0 requested changes

2024-08-05 01:01 UTC, thisisankur0 commented on .eslintrc.cjs
> +    ],
Not achieving anything.
Explore more into this.

2024-08-05 01:01 UTC, thisisankur0 commented
![image](https://github.com/user-attachments/assets/474b2c96-2170-4f62-95e0-4357265fc247)

2024-08-05 03:52 UTC, tiwari00ayush commented on README.md
> +Ensure you have Node.js and pnpm (Package Manager) installed on your machine.
okay

2024-08-05 08:12 UTC, tiwari00ayush commented on .lintstagedrc
> +    "**/*.{ts,tsx,html,css,json}": ["prettier --write"]
okay

2024-08-05 16:56 UTC, tiwari00ayush commented on tsconfig.json
> +    "files": [],
https://github.com/microsoft/TypeScript/issues/49844

I got this error whenever i remove the files option from the base config.

2024-08-05 16:58 UTC, tiwari00ayush commented on tsconfig.json
> +    "files": [],
![Screenshot from 2024-08-05 22-28-31](https://github.com/user-attachments/assets/8b4414a9-7fa0-4b82-bb12-c19f092eea31)

2024-08-05 17:29 UTC, tiwari00ayush commented
https://github.com/jtg-induction/AYUSH_TIWARI_ASSIGNMENT_2/pull/1#discussion_r1702761296

This location is chosen likely because node_modules is ignored by git, and .tmp suggests it's a temporary file used only for the build process. It is not necessary to be in the main folder

2024-08-06 21:31 UTC, thisisankur0 commented on .eslintrc.cjs
> +        'plugin:@typescript-eslint/stylistic',
Remove this, we shouldn't have formatting rules within linter file.

2024-08-06 21:32 UTC, thisisankur0 commented on .lintstagedrc
> +    "**/*": ["prettier --write"]
This will run concurrently, read on why we shouldn't do that.

2024-08-06 22:27 UTC, thisisankur0 requested changes

2024-08-06 22:27 UTC, thisisankur0 commented on tsconfig.app.json
> +    "include": ["src"]
exclude node_modules, if not excluded by default

2024-08-06 22:27 UTC, thisisankur0 commented on tsconfig.json
> +    },
Why is this inside the main tsconfig.json file, shouldn't it be inside .app.json perhaps?

2024-08-06 22:27 UTC, thisisankur0 commented on tsconfig.app.json
> +    "include": ["src"]
Aren't we missing .ts files outside of src. If we are include them as well.
Also don't forget to exclude node_modules as well.

2024-08-06 22:27 UTC, thisisankur0 commented on .eslintrc.cjs
> +        'plugin:import/recommended',
Not set properly, either fix it or remove for now.

2024-08-06 22:27 UTC, thisisankur0 commented on .eslintrc.cjs
> +        '@typescript-eslint/no-non-null-assertion': 'off',
Remove these rules.

2024-08-06 22:27 UTC, thisisankur0 commented on .eslintrc.cjs
> +    },
parserOptions is not a key value here.

2024-08-06 22:27 UTC, thisisankur0 commented on tsconfig.eslint.json
> +}
Not a valid solution.

2024-08-06 22:27 UTC, thisisankur0 commented on vite.config.ts
> +            '@': path.resolve(__dirname, './src'),
Instead of defining it again, can we create a single file and share it here

2024-08-06 22:29 UTC, thisisankur0 commented on .eslintrc.cjs
> +    ],
Skipping this approach, we'll only lint ts and tsx files.

2024-08-06 22:32 UTC, thisisankur0 requested changes

2024-08-06 22:32 UTC, thisisankur0 commented on tsconfig.app.json
> +    "include": ["src"]
Add vite.config.ts as well, since we're using .node.json to parse that file.

2024-08-06 22:33 UTC, thisisankur0 commented on README.md
> +Ensure you have Node.js and pnpm (Package Manager) installed on your machine.
Remove this line

2024-08-07 05:48 UTC, tiwari00ayush commented on .eslintrc.cjs
> +        'plugin:@typescript-eslint/stylistic',
okay.

2024-08-07 06:26 UTC, tiwari00ayush commented on .lintstagedrc
> +    "**/*": ["prettier --write"]
"**/*" this glob pattern will cover all the files which are staged even though we don't include '.' in the command here.

2024-08-07 06:26 UTC, tiwari00ayush commented on .lintstagedrc
> +}
Okay.

2024-08-07 06:29 UTC, tiwari00ayush commented on .eslintrc.cjs
> +        'react/react-in-jsx-scope': 'off',
okay, got it.

2024-08-07 06:31 UTC, tiwari00ayush commented on tsconfig.json
> +    },
Yes, i have already updated that in the next branch. Should i do this here also ?

2024-08-07 06:36 UTC, tiwari00ayush commented on .eslintrc.cjs
> +    },
can you elaborate please

2024-08-07 06:36 UTC, tiwari00ayush commented on tsconfig.eslint.json
> +}
why ?

2024-08-07 07:02 UTC, tiwari00ayush commented on .eslintrc.cjs
> +    },
This suggestion was given by eslint itself

![Screenshot from 2024-08-07 12-28-14](https://github.com/user-attachments/assets/b4efbdfa-9097-431e-a7cc-1a3ee30c4d12)

2024-08-07 07:02 UTC, tiwari00ayush commented on .eslintrc.cjs
> +        '@typescript-eslint/no-non-null-assertion': 'off',
why?

2024-08-07 07:17 UTC, tiwari00ayush commented on .eslintrc.cjs
> +        'plugin:import/recommended',
I am removing it for now

2024-08-07 07:18 UTC, tiwari00ayush commented on tsconfig.eslint.json
> +}
This suggestion was given by eslint itself.

![Screenshot from 2024-08-07 12-28-14](https://github.com/user-attachments/assets/498e6278-b9c1-4ca7-9b4e-287694f7572b)

2024-08-07 07:28 UTC, tiwari00ayush commented
https://github.com/jtg-induction/AYUSH_TIWARI_ASSIGNMENT_2/pull/1#discussion_r1706179835

Why should we add vite file which is only important to node and not to browser, app.json is specific to browser which includes the components reside in the src folder.

2024-08-07 07:35 UTC, tiwari00ayush commented on vite.config.ts
> +            '@': path.resolve(__dirname, './src'),
A single file to share alias between tsconfig.app.json and vite.config.ts ?

2024-08-07 07:36 UTC, tiwari00ayush commented on tsconfig.app.json
> +    "include": ["src"]
Why should we add vite file which is only important to node and not to browser, app.json is specific to browser which includes the components reside in the src folder.

2024-08-07 08:23 UTC, thisisankur0 commented on tsconfig.json
> +    },
Yes

2024-08-07 09:15 UTC, thisisankur0 commented on .lintstagedrc
> +    "**/*": ["prettier --write"]
Discussed in standup, we can also use this flag --ignore-unknown

2024-08-07 12:20 UTC, thisisankur0 commented on vite.config.ts
> +            '@': path.resolve(__dirname, './src'),
Discussed, will be fixed in subsequent PR

2024-08-07 18:00 UTC, thisisankur0 commented on .eslintrc.cjs
> +        'plugin:import/recommended',
Not removed, why is that?

2024-08-07 18:18 UTC, thisisankur0 commented on tsconfig.app.json
> +        "composite": true,
is this required?

2024-08-07 18:25 UTC, thisisankur0 commented on tsconfig.node.json
> +        "composite": true,
Same here is this required?

2024-08-07 18:25 UTC, thisisankur0 commented on README.md
> +Ensure you have Node.js and pnpm (Package Manager) installed on your machine.
This is still not resolved.

2024-08-07 18:30 UTC, thisisankur0 requested changes
Please go through all the unresolved comments, you have missed 1-2 changes suggested in there.

2024-08-08 06:37 UTC, tiwari00ayush commented on tsconfig.node.json
> +        "composite": true,
Yes, when we use two different files to divide the configurations then we have to enable the composite option
![Screenshot from 2024-08-08 12-06-39](https://github.com/user-attachments/assets/19fd75d1-f195-4d8d-94e8-7e3f0fcd343a)

2024-08-08 06:37 UTC, tiwari00ayush commented on tsconfig.app.json
> +        "composite": true,
Yes.

2024-08-08 06:38 UTC, tiwari00ayush commented on readme.md
> +# React dashboard
I have changed it to Admin Dashboard, it it ok ?

2024-08-08 06:39 UTC, tiwari00ayush commented on readme.md
> +This project is a responsive dashboard application built using React, TypeScript, and Material-UI. It provides an intuitive interface to visualize customer data, transactions, and sales performance t
I have removed it.

2024-08-08 06:40 UTC, tiwari00ayush commented on readme.md
> +4. Chart.js
Yes, have removed the 3rd and the 4th one and will update the tech stack with zustand and radix ui in the next PR

2024-08-08 06:40 UTC, tiwari00ayush commented on readme.md
> +
Done

2024-08-08 06:41 UTC, tiwari00ayush commented on .lintstagedrc
> +  "**/*.{ts,tsx,json}": [
I have updated it as discussed

2024-08-08 06:41 UTC, tiwari00ayush commented on .eslintrc.cjs
> +        'plugin:react-hooks/recommended', // extends the react-hooks recommended rules
Okay.

2024-08-08 06:42 UTC, tiwari00ayush commented on .prettierignore
> +node_modules
I have added the lock file now

2024-08-08 06:42 UTC, tiwari00ayush commented on index.html
> +        <title>Vite + React + TS</title>
okay

2024-08-08 06:42 UTC, tiwari00ayush commented on package.json
> +        "preview": "vite preview"
now fixed

2024-08-08 06:44 UTC, tiwari00ayush commented on README.md
> +Ensure you have Node.js and pnpm (Package Manager) installed on your machine.
will remove it now

2024-08-08 08:48 UTC, thisisankur0 commented on tsconfig.node.json
> +        "composite": true,
Incorrect use case, this is used inside a monorepo not for referencing 2 tsconfig files.

2024-08-08 11:48 UTC, thisisankur0 approved these changes

2024-08-08 11:49 UTC, merged