[AT_RU_0_2] Setup of radix, emotion, react router and zustand
jtg-induction/AYUSH_TIWARI_ASSIGNMENT_2 pull request #2
Opened 2024-08-09 10:38 UTC by tiwari00ayush

## Descripitions
1. I have added radix/primitive for components.
2. Added emotion for styling the components.
3. Added routes for different navigation links.
4. Setup a demo store of zustand.

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] Keyboard accessibility
-   [x] Cross browser testing

2024-08-09 20:12 UTC, thisisankur0 commented on pnpm-lock.yaml
This file has merge conflicts defined inside.
For lock file we don't need to resolve them manually, just run ``pnpm install``

2024-08-11 22:33 UTC, thisisankur0 requested changes
Can we have better naming convention for images?
Also why aren't they webp?
![image](https://github.com/user-attachments/assets/bd0f6b51-ce94-431f-9249-bf9a0728edad)

2024-08-11 22:33 UTC, thisisankur0 commented on vite.config.ts
> +            jsxImportSource: '@emotion/react', // add this
Remove this comment.

2024-08-11 22:33 UTC, thisisankur0 commented on tsconfig.app.json
> +            "@/*": ["./src/*"],
Can remove this.

2024-08-11 22:33 UTC, thisisankur0 commented on src/typography.css
> +/* font weight */
Missing Typography component.

2024-08-11 22:33 UTC, thisisankur0 commented on src/index.css
> +html {
Can we keep css file together in a folder?
![image](https://github.com/user-attachments/assets/48a691d6-b9ef-4c8a-a560-f45f5860de8d)

2024-08-11 22:33 UTC, thisisankur0 commented on index.html
> +        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
What are these for?

2024-08-11 22:33 UTC, thisisankur0 commented on package.json
> +        "npm": "^10.8.2",
What are these dependencies?

2024-08-11 22:33 UTC, thisisankur0 commented on src/components/NavLink.tsx
> +};
Nit: Should we defined types and styles within the same file?

2024-08-11 22:33 UTC, thisisankur0 commented on src/router/router.tsx
> +            path="/"
Can we reroute '/' path to redirect to '/overview' page?

2024-08-11 22:33 UTC, thisisankur0 commented on src/components/NavLink.tsx
> +};
```suggestion
const styles = (isActive: boolean) => 
    css({
        color: `${isActive ? colors.green[500] : colors.gray[900]}`,
    });
```

2024-08-11 22:33 UTC, thisisankur0 commented on src/components/NavLink.tsx
> +    children: React.ReactNode;
There is a better way to achieve this.

2024-08-11 22:33 UTC, thisisankur0 commented on src/components/NavLink.tsx
> +import * as NavigationMenu from '@radix-ui/react-navigation-menu';
This will import everything from the file. Can we only import modules that we're using?

2024-08-11 22:33 UTC, thisisankur0 commented on src/theme/index.ts
> +};
Look into how we define casing for constants.

2024-08-11 22:33 UTC, thisisankur0 commented on src/theme/index.ts
> +    sideBarTop: `solid 1px #00000040`,
Can we define colors, if we're going to be repeating them?

2024-08-11 22:33 UTC, thisisankur0 commented on src/router/router.tsx
> +                <Route path="productlist" element={<span>Product list</span>} />
```suggestion
                <Route path="product-list" element={<span>Product list</span>} />
```

2024-08-11 22:33 UTC, thisisankur0 commented on src/router/router.tsx
> +                <Route path="page1" element={<span>Page 1</span>} />
Add better name

2024-08-11 22:33 UTC, thisisankur0 commented on src/index.css
> +    font-optical-sizing: auto;
Why are we writing default values?

2024-08-11 22:33 UTC, thisisankur0 commented on src/components/IconButton.tsx
> +        </button>
https://ui.shadcn.com/docs/components/button

2024-08-12 06:40 UTC, tiwari00ayush commented
https://github.com/jtg-induction/AYUSH_TIWARI_ASSIGNMENT_2/pull/2#pullrequestreview-2230989353

For name - i will update it.
it is png because png are optimized for images with transparent background, reference : https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#png_portable_network_graphics

2024-08-12 06:41 UTC, tiwari00ayush commented on pnpm-lock.yaml
>      dependencies:
i did that, somehow it get missed, i will try not to repeat that.

2024-08-12 06:50 UTC, tiwari00ayush commented on vite.config.ts
> +            '@store': path.resolve(__dirname, './src/store'),
yes, i will update it now.

2024-08-12 06:50 UTC, tiwari00ayush commented on src/App.tsx
>  function App() {
Yes, sure

2024-08-12 06:52 UTC, tiwari00ayush commented on src/assets/icons/noti.svg
> +<svg width="18" height="21" viewBox="0 0 18 21" fill="none" xmlns="http://www.w3.org/2000/svg">
okay

2024-08-12 06:55 UTC, tiwari00ayush commented on tsconfig.app.json
> +            "@/*": ["./src/*"],
like we have to import App file into the main file, we can use this notation(@/App.tsx) for that instead of ./src/App.tsx ?

2024-08-12 07:06 UTC, tiwari00ayush commented on src/index.css
> +html {
Okay.

2024-08-12 07:06 UTC, tiwari00ayush commented on index.html
> +        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
its for font

2024-08-12 07:07 UTC, tiwari00ayush commented on package.json
> +        "npm": "^10.8.2",
will remove it, got install it by mistake when running the comand npm i instead of pnpm i

2024-08-12 07:08 UTC, tiwari00ayush commented on src/router/router.tsx
> +            path="/"
Yes

2024-08-12 07:08 UTC, tiwari00ayush commented on src/components/NavLink.tsx
> +};
okay

2024-08-12 07:11 UTC, tiwari00ayush commented on src/components/NavLink.tsx
> +    children: React.ReactNode;
Are you talking about react.fc ? if yes i have explored it but there was a discussion that it is not a optimal choice therefore i used it: https://github.com/facebook/create-react-app/pull/8177

if no, i will explore it further

2024-08-12 07:13 UTC, tiwari00ayush commented on src/components/NavLink.tsx
> +import * as NavigationMenu from '@radix-ui/react-navigation-menu';
Yes sure

2024-08-12 07:18 UTC, tiwari00ayush commented on src/index.css
> +    font-optical-sizing: auto;
then the browser will modify the shape of glyphs for optimal viewing.

2024-08-12 07:31 UTC, tiwari00ayush commented on src/components/IconButton.tsx
> +        </button>
can we use shadcn component in radix ?

2024-08-12 12:20 UTC, tiwari00ayush commented on src/components/NavLink.tsx
> +};
Styles in the same file, because we are css in js and for types, our project is small and our component will not going to be that long that we have to end by dividing it in seprate files, even radix is declaring types and interface in the same file. So I would look to go with same file

2024-08-12 12:24 UTC, thisisankur0 commented on src/components/NavLink.tsx
> +};
Makes it very unreadable IMO. Not now but if we take scalability in perspective. We'll have to update the same everywhere.
Same going through this file will be pain:  https://github.com/radix-ui/primitives/blob/main/packages/react/context-menu/src/ContextMenu.tsx

2024-08-12 12:25 UTC, thisisankur0 commented on src/components/NavLink.tsx
> +    children: React.ReactNode;
Discussed.

2024-08-12 12:25 UTC, thisisankur0 commented on src/components/IconButton.tsx
> +        </button>
Discussed

2024-08-12 12:26 UTC, tiwari00ayush commented on src/components/NavLink.tsx
> +};
okay!

2024-08-12 12:34 UTC, tiwari00ayush commented on src/components/NavLink.tsx
> +};
I am not doing this for counter element because it will be deleted in the next pr

2024-08-13 10:23 UTC, tiwari00ayush commented on src/router/router.tsx
> +            path="/"
can we open the overview component directly on the home route, as we don't have anyother specific component for home route ?, like this : 
```js
        <Route
            path="/"
            element = {<Layout/>}
            errorElement={<h1>Error page</h1>}
        >
            <Route index element={<h1>Overview</h1>} />
```

2024-08-13 10:25 UTC, tiwari00ayush commented on src/router/router.tsx
> +            path="/"
Now, there will be no "/overview" route seprately, user can visit directly the overview page by going to home page

2024-08-13 10:32 UTC, tiwari00ayush commented on src/router/router.tsx
> +            path="/"
okay!

2024-08-13 17:37 UTC, thisisankur0 commented on src/theme/index.ts
> +};
```suggestion
export const radius = {
    'ROUNDED_FULL': '50%',
    'ROUNDED_2XL': '16px',
    'ROUNDED_XL': '10px',
};
```

2024-08-13 17:39 UTC, thisisankur0 commented on src/theme/index.ts
> +};
We won't be needing these many breakpoints

```suggestion
export const breakpoints = {
    MOBILE: '320px',
    TABLET: '768px',
    SMALL_DESKTOP: '1024px',
    DESKTOP: '1440px',
    LARGE_DESKTOP: '1920px',
};
```

2024-08-13 17:44 UTC, thisisankur0 commented on src/App.tsx
```suggestion
const App = () => <RouterProvider router={router} />;
```

2024-08-13 17:47 UTC, thisisankur0 commented on src/main.tsx
> +import App from './App';
```suggestion
import {StrictMode} from 'react';
import {createRoot} from 'react-dom/client';
import App from './App';
```

2024-08-13 17:57 UTC, thisisankur0 commented on src/components/IconButton/IconButton.tsx
> +);
Nit:

```suggestion
const IconButton = React.forwardRef<HTMLButtonElement, IconButtonProps>(
    ({asChild = false, ...props}, ref) => {
        const Comp = asChild ? Slot : 'button';
        
        return <Comp ref={ref} {...props} css={style} />;
    },
);
```

2024-08-13 18:23 UTC, thisisankur0 commented on src/components/IconButton/IconButton.tsx
> +
Can we keep styles in a different file also?

2024-08-13 18:26 UTC, thisisankur0 commented on src/components/Typography/Typography.tsx
> +export const styles = {
Missing Linting error

2024-08-13 18:27 UTC, thisisankur0 commented on src/components/Typography/Typography.tsx
> +
```suggestion
const Typography = ({component:Component = 'p', children, css: overrideCss}: PropsWithChildren<TypographyProps>) => <Component css={[styles[Component], overrideCss]}>{children}</Component>;
```

2024-08-13 18:29 UTC, thisisankur0 commented on src/components/Typography/Typography.tsx
> +import {PropsWithChildren} from 'react';
Remove it from here.

2024-08-13 18:30 UTC, thisisankur0 commented on src/theme/index.ts
> +
Create a constant for Font weight as well.

2024-08-13 18:40 UTC, thisisankur0 commented on src/theme/index.ts
> +
```suggestion
export const borders = {
    GRAY_1: `solid 1px ${colors.GRAY[200]}`,
    BLACK_1: `solid 1px ${colors.BLACK[200]}`,
};

```

2024-08-13 18:43 UTC, thisisankur0 commented on src/components/NavLink/NavLink.tsx
> +        fontSize: '1.6rem',
```suggestion
        color: isActive ? colors.GREEN[500] : colors.GRAY[900],
```

2024-08-13 21:09 UTC, thisisankur0 requested changes

2024-08-13 21:09 UTC, thisisankur0 commented on src/router/router.tsx
> +                        })}
This should work without the css function call as well.

2024-08-13 21:09 UTC, thisisankur0 commented on src/components/Typography/Typography.tsx
> +
I read more into this: https://emotion.sh/docs/css-prop#style-precedence
Overriding it using the overrideCss prop is not the intended behavior by them, but a hacky way.
```suggestion

const Typography = ({component, children, className}: PropsWithChildren<TypographyProps>) => {
    const Comp = component ?? 'p';

    return <Comp css={styles[Comp]} className={className}>{children}</Comp>;
};

```
And pass in the CSS prop only on the Typography component

2024-08-13 21:09 UTC, thisisankur0 commented on src/router/router.tsx
> +                        })}
```suggestion
                    <Typography
                        component="h1"
                        css={{
                            color: 'red',
                        }}
```

2024-08-13 21:09 UTC, thisisankur0 commented on index.html
>          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
Missing favicon file.

2024-08-14 02:21 UTC, tiwari00ayush commented on src/theme/index.ts
> +};
Just in case.

2024-08-14 02:39 UTC, tiwari00ayush commented on tsconfig.app.json
>          "baseUrl": ".",
I am removing this baseurl, as i explored i found that it is not needed for setting path alias.
![Screenshot from 2024-08-14 08-08-04](https://github.com/user-attachments/assets/cc6ee0b8-a819-4e5d-bb71-c6ca1feb606c)
link https://www.typescriptlang.org/tsconfig/#baseUrl

2024-08-14 03:20 UTC, tiwari00ayush commented on src/components/NavLink/NavLink.tsx
> +);
in order to style the link using only emotion, i have to pass the active state variable but it is present only in the classname, i can't access outside classname prop

2024-08-14 06:11 UTC, tiwari00ayush commented on src/components/Typography/Typography.tsx
> +
didn't understand

2024-08-14 06:20 UTC, tiwari00ayush commented on vite.config.ts
> +        react({
Okay.

2024-08-14 06:22 UTC, tiwari00ayush commented on src/components/NavLink/NavLink.tsx
> +        color: `${isActive ? colors.GREEN[500] : colors.GRAY[900]}`,
okay

2024-08-14 06:24 UTC, tiwari00ayush commented on src/components/Typography/Typography.tsx
> +import {PropsWithChildren} from 'react';
remove what ?

2024-08-14 06:24 UTC, tiwari00ayush commented on src/theme/index.ts
> +};
okay

2024-08-14 07:37 UTC, thisisankur0 commented on src/components/Typography/Typography.tsx
> +import {PropsWithChildren} from 'react';
PropsWithChildren

2024-08-14 09:20 UTC, tiwari00ayush commented on tsconfig.app.json
>          "baseUrl": ".",
updated now as discussed

2024-08-14 09:20 UTC, tiwari00ayush commented on src/theme/index.ts
> +);
okay

2024-08-14 13:48 UTC, thisisankur0 commented on src/components/NavLink/NavLink.tsx
> +);
```suggestion
const NavLink = React.forwardRef<HTMLAnchorElement, NavLinkProps>(
    ({to, children, ...props}, ref) => (
        <RadixLink asChild>
            <RouterLink to={to} css={styles} ref={ref} {...props}>
                {children}
            </RouterLink>
        </RadixLink>
    ),
```

2024-08-14 13:50 UTC, thisisankur0 commented on src/components/NavLink/NavLink.tsx
> +import {NavLink as RouterLink} from 'react-router-dom';
```suggestion
import { forwardRef } from 'react';
```

2024-08-14 13:51 UTC, thisisankur0 commented on src/components/IconButton/IconButton.tsx
> + */
docs are defined above component, why is it defined here.

2024-08-14 13:51 UTC, thisisankur0 commented on src/components/IconButton/IconButton.tsx
> + * IconButton Component
```suggestion
/**
```

2024-08-14 13:51 UTC, thisisankur0 commented on src/components/IconButton/IconButton.tsx
> +    padding: '0.6rem 0.7rem',
```suggestion
    borderRadius: radius.FULL,
    boxShadow: boxShadow.MD,
```

2024-08-14 13:53 UTC, thisisankur0 commented on src/components/Typography/Typography.tsx
> + */
Same

2024-08-14 13:54 UTC, thisisankur0 commented on src/App.tsx
```suggestion
const App = () => <RouterProvider router={router} />;
```

2024-08-14 13:55 UTC, thisisankur0 commented on src/components/IconButton/IconButton.tsx
> +import {Slot} from '@radix-ui/react-slot';
```suggestion
import { forwardRef } from 'react';
```

2024-08-14 14:40 UTC, thisisankur0 commented on src/components/IconButton/IconButton.tsx
> +
Missing space

2024-08-14 14:43 UTC, thisisankur0 commented on src/components/Typography/Typography.tsx
> + */
Not updated

2024-08-14 14:44 UTC, thisisankur0 commented on src/theme/index.ts
> + * @type {Map<keyof typeof breakpoints, string>}
Not required please remove this line.

2024-08-14 14:48 UTC, thisisankur0 commented on src/components/IconButton/IconButton.tsx
> +    padding: '0.6px 0.7px',
Won't this be 6px and 7px respectively?

2024-08-16 05:45 UTC, tiwari00ayush commented on src/components/IconButton/IconButton.tsx
> +
which space

2024-08-16 05:45 UTC, tiwari00ayush commented on src/components/IconButton/IconButton.tsx
> +    padding: '0.6px 0.7px',
yes

2024-08-16 06:59 UTC, thisisankur0 approved these changes

2024-08-16 07:01 UTC, merged