[AT_RU_1_1] Navbar of admin dashboard
jtg-induction/AYUSH_TIWARI_ASSIGNMENT_2 pull request #3
Opened 2024-08-13 14:34 UTC by tiwari00ayush

## Descripitions

## Live Link 
https://66bb6d56b2c61f30930d047f--candid-paprenjak-99bdf4.netlify.app/overview

## Screenshots or Recordings
![Screenshot from 2024-08-13 20-01-24](https://github.com/user-attachments/assets/3ba9ace0-ced0-4103-985c-6b962591fd33)
![Screenshot from 2024-08-13 20-04-40](https://github.com/user-attachments/assets/110041fe-5f25-4580-b33c-1f50227decff)

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] Keyboard accessibility
-   [x] Cross browser testing

![Screenshot from 2024-08-13 20-04-31](https://github.com/user-attachments/assets/43c5789a-b369-4a71-930d-5e121abc45ad)

2024-08-16 12:28 UTC, thisisankur0 commented on src/assets/icons/cross-icon.svg
> +</svg>
Missing EOF

2024-08-16 19:08 UTC, thisisankur0 requested changes

2024-08-16 19:08 UTC, thisisankur0 commented on src/components/SearchBar/SearchBar.tsx
> +                            ))}
Invalid HTML validation

2024-08-16 19:08 UTC, thisisankur0 commented on src/components/SearchBar/SearchBar.tsx
> +                <ScrollArea.Root css={styles.scrollArea} style={{position: 'absolute'}}>
Add comment on why this was implemented.

2024-08-16 19:08 UTC, thisisankur0 commented on src/components/SearchBar/SearchBar.tsx
> +                                <Link to={'/products'} css={styles.resultItem} key={data.id}>
Getting this error page.
![image](https://github.com/user-attachments/assets/f9075f62-b7e2-4d30-b489-1497b96efb3d)

2024-08-16 19:10 UTC, thisisankur0 commented on src/store/SearchStore/searchStore.ts
> +    searchResult: () => {
This can be optimised, check on what we should store inside global store.

2024-08-16 19:13 UTC, thisisankur0 commented on src/components/Navbar/Navbar.tsx
> +                                <img src={photoURL} alt="profile picture" css={styles.profilePic} />
Also the arrow icon is misaligned.

2024-08-16 19:15 UTC, thisisankur0 commented on src/store/SearchStore/searchStore.ts
> +interface dummyDataType {
Can only search on product name skip framework.

2024-08-17 11:53 UTC, tiwari00ayush commented on src/layouts/Layout.tsx
> +        </div>
Yes we can remove this.

2024-08-17 13:27 UTC, tiwari00ayush commented on src/components/Navbar/Navbar.tsx
> +import {radius, boxShadow, colors} from '@theme/index';
it was used before IE, but not only icon will suffice.

2024-08-17 13:46 UTC, tiwari00ayush commented on src/components/Navbar/Navbar.tsx
> +            <Separator css={styles.seprator} />
it full fill these requirements

https://www.w3.org/TR/wai-aria-1.2/#separator

2024-08-17 13:52 UTC, tiwari00ayush commented on src/components/Navbar/Navbar.tsx
> +                                <img src={photoURL} alt="profile picture" css={styles.profilePic} />
arrow icons looks good to me, like should i shift to right or in the middle ?

2024-08-17 14:05 UTC, tiwari00ayush commented on src/store/SearchStore/searchStore.ts
> +interface dummyDataType {
I was thinking of using the same data in product list, so can we let it stay as it is

2024-08-17 16:04 UTC, tiwari00ayush commented on src/components/SearchBar/SearchBar.tsx
> +                                <Link to={'/products'} css={styles.resultItem} key={data.id}>
We don't have to direct the products to somewhere else, that's why i connected it to the error page

2024-08-17 16:05 UTC, tiwari00ayush commented on src/components/SearchBar/SearchBar.tsx
> +                                <Link to={'/products'} css={styles.resultItem} key={data.id}>
routes for every product like "/product-uikit" ?

2024-08-17 16:07 UTC, tiwari00ayush commented on src/components/SearchBar/SearchBar.tsx
> +    }),
this design was particular to search bar, I have styled a similair for the main page

2024-08-17 16:08 UTC, tiwari00ayush commented on src/components/SearchBar/SearchBar.tsx
> +        },
GRAY.100 ?

2024-08-17 18:08 UTC, tiwari00ayush commented on src/store/SearchStore/searchStore.ts
> +];
will the structure of product change?

2024-08-17 18:34 UTC, tiwari00ayush commented on src/components/SearchBar/SearchBar.tsx
> +import {radius, borders, boxShadow, colors, mq} from '@theme/index';
index files are generally used as barrel files, therefore i have used to export all constants

2024-08-17 20:20 UTC, thisisankur0 commented on src/components/SearchBar/SearchBar.tsx
> +        },
Leave 1 line between hover styles and the styles defined above it.

2024-08-17 20:21 UTC, thisisankur0 commented on src/components/SearchBar/SearchBar.tsx
> +    }),
Can use the same for the sidebar as well.

2024-08-17 20:27 UTC, thisisankur0 commented on src/components/Navbar/Navbar.tsx
> +            <Separator css={styles.seprator} />
It's mentioned: "A divider that separates and distinguishes sections of content or groups of menuitems."
We're doing neither of these things here.

2024-08-17 20:28 UTC, thisisankur0 commented on src/components/Navbar/Navbar.tsx
> +                                <img src={photoURL} alt="profile picture" css={styles.profilePic} />
a little bit more to the right.

2024-08-17 20:29 UTC, thisisankur0 commented on src/store/SearchStore/searchStore.ts
> +interface dummyDataType {
Yes, was just talking about in the context of search logic.
My bad mentioned on the wrong line.

2024-08-17 20:30 UTC, thisisankur0 commented on src/components/SearchBar/SearchBar.tsx
> +                                <Link to={'/products'} css={styles.resultItem} key={data.id}>
Leave it as is for now. 
But ideally it should have been /product/uikit.

2024-08-17 20:31 UTC, thisisankur0 commented on src/components/SearchBar/SearchBar.tsx
> +import {radius, borders, boxShadow, colors, mq} from '@theme/index';
Can you elaborate more on this.

2024-08-18 05:59 UTC, tiwari00ayush commented on src/components/SearchBar/SearchBar.tsx
> +import {radius, borders, boxShadow, colors, mq} from '@theme/index';
to export all the theme related things from a single file i have used index inside theme folder. because index files are generally used as barrel files

2024-08-18 06:00 UTC, tiwari00ayush commented on src/components/SearchBar/SearchBar.tsx
> +                                <Link to={'/products'} css={styles.resultItem} key={data.id}>
okay

2024-08-18 06:39 UTC, tiwari00ayush commented on src/store/SearchStore/searchStore.ts
> +    searchResult: () => {
I have provide single source of truth for query as well as, so that we know how the value changes 
and if set the query using usestate in that component then it can create problem, as the current state of the query may update after search result is called

2024-08-18 07:26 UTC, thisisankur0 commented on src/store/SearchStore/searchStore.ts
> +    searchResult: () => {
we're using event handlers for this, we'll have the updated query every time. No need to store everything in a global state.

2024-08-21 05:52 UTC, thisisankur0 requested changes

2024-08-21 05:52 UTC, thisisankur0 commented on src/components/Navbar/Navbar.tsx
> +                        </Portal>
Like mentioned in the previous comment, remove this component from here and create an avatar component which supports onClick functionality.

2024-08-21 05:52 UTC, thisisankur0 commented on src/components/Navbar/Navbar.tsx
> +                                    <Typography component="h4">{email}</Typography>
![image](https://github.com/user-attachments/assets/85840b56-295d-442e-97dd-60698e2a935b)

2024-08-21 05:52 UTC, thisisankur0 commented on src/components/SearchBar/SearchBar.tsx
> + * @todo replace with combobox
```suggestion
 * TODO: replace with combobox
```

2024-08-21 05:52 UTC, thisisankur0 commented on src/store/SearchStore/searchStore.data.ts
> +];
use as const or satisfy

2024-08-21 05:52 UTC, thisisankur0 commented on src/store/SearchStore/searchStore.data.ts
> +export const ProductData: ProductType[] = [
This inference doesn't do anything. Remove it.

2024-08-21 05:52 UTC, thisisankur0 commented on src/store/SearchStore/searchStore.ts
> +import {create} from 'zustand';
Where is the common store which was mentioned in the previous comment: https://zustand.docs.pmnd.rs/guides/flux-inspired-practice#single-store

2024-08-21 05:58 UTC, tiwari00ayush commented on src/css/index.css
> +}
I am giving this style to the scrollbar component i am using from the radix ui, they have a seprate component for scrollbar and thumb, and i am trying to pass the styles directly to them, by modifying styling of global scrollbar, it will not impact the custom scrollbar provided by radix

2024-08-21 06:36 UTC, tiwari00ayush commented on src/store/SearchStore/searchStore.ts
> +}));
```ts
<input
                placeholder="Search"
                css={styles.inputBar}
                value={query}
                onChange={handleChange}
                onFocus={() => setIsResultsOpen(true)}
            />
```
i am using the state so that it can passed to the value of the input

2024-08-21 06:49 UTC, tiwari00ayush commented on src/store/SearchStore/searchStore.ts
> +import {create} from 'zustand';
it is saying to colocate state and function in the same file, and i have done the same thing, 
e.g. https://github.com/maulik9898/barrage/blob/main/stores/useTableStore.ts

2024-08-21 06:51 UTC, tiwari00ayush commented on src/store/SearchStore/searchStore.data.ts
> +export const ProductData: ProductType[] = [
![image](https://github.com/user-attachments/assets/9e988f06-232c-45a2-8aa1-b45fc1a074ca)
it is showing error if the next element of the array does not contain the same properties, can you please tell me what unexpected behaviour we have to stop with the help of satisfies ?

2024-08-21 22:41 UTC, thisisankur0 requested changes

2024-08-21 22:41 UTC, thisisankur0 commented on src/utils/routes.ts
> +} as const;
Not following the convention for constants we have created.

2024-08-21 22:41 UTC, thisisankur0 commented on src/utils/routes.ts
> +export const routes = {
Not a util. Create a constants folder.

2024-08-21 22:41 UTC, thisisankur0 commented on src/components/Avatar/Avatar.tsx
> +            boxShadow: boxShadow.MD,
Nit: Spacing between hover styles and color missing, We're following this convention everywhere.

2024-08-21 22:41 UTC, thisisankur0 commented on src/components/Navbar/Navbar.tsx
> +        [mq.SMALL_DESKTOP]: {
Nit: Same here.

2024-08-21 22:41 UTC, thisisankur0 commented on src/components/SearchBar/SearchBar.tsx
> +            {/* to handle click outside of search box */}
Nit;Mention it on the state rather than here.

2024-08-21 22:41 UTC, thisisankur0 commented on src/utils/routes.ts
> +    },
Remove sales and pages root and flatten the object to single level:
productList: '/product-list'

2024-08-21 22:41 UTC, thisisankur0 commented on tsconfig.app.json
> +            "@*": ["*/index"], // https://github.com/microsoft/TypeScript/issues/26859#issuecomment-2048100510
Document a little bit of the issue, then the link of the issue.

2024-08-21 22:41 UTC, thisisankur0 commented on src/components/Popover/Popover.tsx
> +};
This component is mixing business logic, either move it back to navbar or generalize it like shadcn does.

2024-08-22 06:05 UTC, tiwari00ayush commented on src/components/Popover/Popover.tsx
> +};
I am not able to understand why

2024-08-22 09:23 UTC, thisisankur0 approved these changes

2024-08-22 09:23 UTC, thisisankur0 commented on tsconfig.app.json
> +            // https://github.com/microsoft/TypeScript/issues/26859#issuecomment-2048100510
Nit: Multi-line comment

2024-08-22 09:26 UTC, merged