[AT_RU_3] Gallery component
jtg-induction/AYUSH_TIWARI_ASSIGNMENT_2 pull request #5
Opened 2024-08-19 16:25 UTC by tiwari00ayush

## Descripitions
1. Added gallery section

## Live Link
https://66c370609e501a04ed6134a5--dapper-speculoos-e087da.netlify.app/

## Screenshots or Recordings
![image](https://github.com/user-attachments/assets/81bf8464-e147-4b67-991c-f9a0e62ca239)
![image](https://github.com/user-attachments/assets/e6c5e257-cc31-432d-8150-9ca0e24cf87c)

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] Keyboard accessibility
-   [x] Cross browser testing

2024-08-24 23:15 UTC, thisisankur0 requested changes

2024-08-25 07:26 UTC, tiwari00ayush commented on src/components/Gallery/Gallery.tsx
> +const styles = {
I tried using grid but the image getting distorted somehow that's why i shifted to flex to achieve the same.

2024-08-25 09:54 UTC, thisisankur0 commented on src/components/Gallery/Gallery.tsx
> +export const Gallery = () => {
Add a tablet view to avoid distortion.

2024-08-25 12:23 UTC, tiwari00ayush commented on src/components/Gallery/Gallery.tsx
> +export const Gallery = () => {
using this as a tablet will work ?

![image](https://github.com/user-attachments/assets/d6ec7433-a60a-4260-9746-e26251e3ec84)

2024-08-25 14:14 UTC, thisisankur0 commented on src/components/Gallery/Gallery.tsx
> +export const Gallery = () => {
Yes

2024-08-25 17:42 UTC, thisisankur0 approved these changes

2024-08-25 18:02 UTC, merged